---
title: "tfg_results_microscopia"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
library(ggplot2)
library(jpeg)
library(grid)
```

## Quantification

```{r echo=FALSE}
pixels_koct<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_koct.csv")
colnames(pixels_koct)<-c('koct')

pixels_kohfd<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_kohfd.csv")
colnames(pixels_kohfd)<-c('kohfd')

pixels_wtct<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_wtct.csv")
colnames(pixels_wtct)<-c('wtct')

pixels_wthfd<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_wthfd.csv")
colnames(pixels_wthfd)<-c('wthfd')

pixels_hfd<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_hfd.csv")
colnames(pixels_hfd)<-c('hfd')

pixels_ct<-read.csv("/Users/ClaudiaPera/Desktop/TFG/matlab/listas/pixels_lipidos_ct.csv")
colnames(pixels_ct)<-c('ct')
```

```{r echo=FALSE}
#df_pixels_list <- list(pixels_koct$koct, pixels_kohfd$kohfd, pixels_wtct$wtct, pixels_wthfd$wthfd, pixels_hfd$hfd, pixels_ct$ct)

# Convertimos el objeto a un dataframe
#df_pixels <- data.frame(valor = unlist(df_pixels_list),
                      # grupo = rep(names(df_pixels_list), times = sapply(df_pixels_list, length)))
#png("/home/guest/msidata2/TFG_Claudia/plots_resultados.png", width = 800, height = 600)

grafico1 <- ggplot(pixels_koct, aes(x = "", y = koct)) + 
  geom_boxplot()+ 
  geom_text(aes(x = 1.7, y = median(koct), label = paste(round(median(koct),2))), 
            hjust = 1.2, size = 4) +
  labs(x = "KOCT", y = "")
#grafico1
#ggsave("/home/guest/msidata2/TFG_Claudia/plots_resultados/matlab/matlab_koct1.jpg", plot = grafico1)
#dev.off()

grafico2 <- ggplot(pixels_kohfd, aes(x = "", y = kohfd)) + 
  geom_boxplot()+ 
  geom_text(aes(x = 1.7, y = median(kohfd), label = paste(round(median(kohfd),2))), 
            hjust = 1.2, size = 4) +
  labs(x = "KOHFD", y = "") 
#ggsave("/home/guest/msidata2/TFG_Claudia/plots_resultados/matlab/matlab_kohfd.jpg", plot = grafico2)
#grafico2

grafico3 <- ggplot(pixels_wthfd, aes(x = "", y = wthfd)) + 
  geom_boxplot()+ 
  geom_text(aes(x = 1.7, y = median(wthfd), label = paste(round(median(wthfd),2))), 
            hjust = 1.2, size = 4) +
  labs(x = "WTHFD", y = "") 
#ggsave("/home/guest/msidata2/TFG_Claudia/plots_resultados/matlab/matlab_wthfd.jpg", plot = grafico3)
#grafico3

grafico4 <- ggplot(pixels_wtct, aes(x = "", y = wtct)) + 
  geom_boxplot()+ 
  geom_text(aes(x = 1.7, y = median(wtct), label = paste(round(median(wtct),2))), 
            hjust = 1.2, size = 4) +
  labs(x = "WTCT", y = "") 
#ggsave("/home/guest/msidata2/TFG_Claudia/plots_resultados/matlab/matlab_wtct1.jpg", plot = grafico4)
#grafico4


# total_box <- grid.arrange(titulo_general ,grafico1, grafico2, grafico4, grafico3, ncol = 2, nrow=3)
# 
# # agrega un título general
# titulo_general <- textGrob("Total lipid proportion in each sample grouped by group", gp = gpar(fontsize = 14, fontface = "bold"))
# titulo_box <- arrangeGrob(titulo_general, ncol = 1)
# 
# # combina el título general con los gráficos
# grid.arrange(titulo_box, grid.arrange(grafico1, grafico2, grafico4, grafico3, ncol = 2), ncol = 1, heights = c(0.09, 0.9))
# #ggsave("/home/guest/msidata2/TFG_Claudia/plots_resultados/matlab/matlab_total.jpg", plot = total_box)


cat("Total lipid proportion in each sample grouped by group ")
grid.arrange(grafico1, grafico2, grafico4, grafico3, ncol = 2)


```